---
- name: Installation de logiciels...
  hosts: arno
  tasks:
    - name: installation alfred
      homebrew_cask:
        name: alfred
        state: present
        install_options: "appdir=/Applications"
        update_homebrew: yes
...
